// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestPractice.Models;

namespace TestPractice.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    partial class EmployeeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestPractice.Models.Employee", b =>
                {
                    b.Property<int>("EMPID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DEPT")
                        .HasColumnType("varchar(6)");

                    b.Property<DateTime>("HIREDATE")
                        .HasColumnType("datetime");

                    b.Property<string>("JOBCODE")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("SALARY")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("SEX")
                        .HasColumnType("varchar(10)");

                    b.HasKey("EMPID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("TestPractice.Models.EmployeeData", b =>
                {
                    b.Property<int>("EMPID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BIRTHDATE")
                        .HasColumnType("datetime");

                    b.Property<string>("FIRSTNAME")
                        .HasColumnType("varchar(12)");

                    b.Property<string>("LASTNAME")
                        .HasColumnType("varchar(16)");

                    b.Property<string>("PHONE")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 64)))
                        .HasColumnType("varchar(12)");

                    b.HasKey("EMPID");

                    b.ToTable("EmployeeDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
